version: '3'

services:
  db:
    image: postgres:10
    volumes:
      - fixer-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fixer

  web:
    build:
      context: ./app
    command: unicorn -c config/unicorn.rb
    entrypoint: bin/wait-for-it.sh db:5432 -s --
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    ports:
      - '8080:8080'
    links:
      - db
    logging:
      options:
        max-size: "50m"
        max-file: "10"
    restart: unless-stopped
    networks:
      - fixer

  scheduler:
    build:
      context: ./app
    command: bin/schedule
    entrypoint: bin/wait-for-it.sh db:5432 -s --
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    links:
      - db
    logging:
      options:
        max-size: "50m"
        max-file: "10"
    restart: unless-stopped
    networks:
      - fixer

volumes:
  fixer-data:

networks:
  fixer:
